"""
AI schemas — request/response models and structured LLM output schemas.

All LLM responses are validated against these Pydantic models before
being returned to the caller. Free-form text from the LLM is never
accepted without validation.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, Field

# ── Structured LLM Output Schemas ────────────────────────────────────────────


class ExtractedEntity(BaseModel):
    """A single entity extracted from evidence by the LLM."""

    type: str = Field(..., description="Entity type (person, email, ip, domain, etc.)")
    label: str = Field(..., min_length=1, max_length=500, description="Entity label/value")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Confidence score")
    context: str | None = Field(None, max_length=1000, description="Surrounding context from the evidence")
    evidence_ref: str | None = Field(None, max_length=200, description="Reference to specific evidence excerpt")


class ExtractedEntitiesResult(BaseModel):
    """Collection of entities extracted from evidence."""

    entities: list[ExtractedEntity] = Field(default_factory=list, description="Extracted entities")


class SuggestedRelationship(BaseModel):
    """A relationship between entities suggested by the LLM."""

    source_entity_label: str = Field(..., min_length=1, max_length=500, description="Label/name of the source entity")
    target_entity_label: str = Field(..., min_length=1, max_length=500, description="Label/name of the target entity")
    relationship_type: str = Field(..., max_length=100, description="Type of relationship")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Confidence score")
    reasoning: str | None = Field(None, max_length=2000, description="Why the LLM suggests this relationship")
    evidence_ref: str | None = Field(None, max_length=200, description="Reference to supporting evidence")


class SuggestedRelationshipsResult(BaseModel):
    """Collection of suggested relationships."""

    relationships: list[SuggestedRelationship] = Field(default_factory=list)


class TimelineEvent(BaseModel):
    """A chronological event extracted by the LLM."""

    date: str | None = Field(None, max_length=100, description="Date or timestamp of the event")
    title: str = Field(..., min_length=1, max_length=500, description="Event title")
    description: str | None = Field(None, max_length=5000, description="Event description")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Confidence score")
    evidence_ref: str | None = Field(None, max_length=200, description="Reference to supporting evidence")


class GeneratedTimelineResult(BaseModel):
    """Collection of timeline events."""

    events: list[TimelineEvent] = Field(default_factory=list)


class SummaryResult(BaseModel):
    """Evidence summary produced by the LLM."""

    summary: str = Field(..., min_length=1, max_length=50000, description="Concise summary of the evidence")
    key_points: list[str] = Field(default_factory=list, description="Key points extracted from the evidence")


class Finding(BaseModel):
    """A finding or conclusion from the investigation."""

    title: str = Field(..., min_length=1, max_length=500, description="Finding title")
    description: str = Field(..., min_length=1, max_length=5000, description="Finding description")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Confidence")
    evidence_refs: list[str] = Field(default_factory=list, description="References to supporting evidence")


class Recommendation(BaseModel):
    """A recommendation for next steps."""

    title: str = Field(..., min_length=1, max_length=500, description="Recommendation title")
    description: str = Field(..., min_length=1, max_length=5000, description="Recommendation details")
    priority: str = Field(default="medium", pattern="^(low|medium|high|critical)$", description="Priority level")


class ReportResult(BaseModel):
    """Complete investigation report generated by the LLM."""

    executive_summary: str = Field(..., min_length=1, max_length=10000, description="High-level summary")
    evidence_summary: str = Field(..., min_length=1, max_length=20000, description="Evidence overview")
    timeline: list[TimelineEvent] = Field(default_factory=list, description="Chronological events")
    entities: list[ExtractedEntity] = Field(default_factory=list, description="Entities identified")
    relationships: list[SuggestedRelationship] = Field(default_factory=list, description="Relationships identified")
    findings: list[Finding] = Field(default_factory=list, description="Investigation findings")
    recommendations: list[Recommendation] = Field(default_factory=list, description="Recommended actions")


# ── API Request Schemas ───────────────────────────────────────────────────────


class AISummarizeRequest(BaseModel):
    """Request to summarize evidence."""

    evidence_id: uuid.UUID = Field(..., description="UUID of the evidence to summarize")
    max_length: int | None = Field(None, ge=50, le=10000, description="Maximum summary length in characters")


class AIExtractEntitiesRequest(BaseModel):
    """Request to extract entities from evidence."""

    evidence_id: uuid.UUID = Field(..., description="UUID of the evidence to analyze")
    investigation_id: uuid.UUID | None = Field(None, description="UUID of the investigation (required for suggestions)")


class AIRelationshipsRequest(BaseModel):
    """Request to suggest relationships for entities in an investigation."""

    investigation_id: uuid.UUID = Field(..., description="UUID of the investigation")
    evidence_ids: list[uuid.UUID] | None = Field(None, max_length=50, description="Specific evidence to analyze")


class AITimelineRequest(BaseModel):
    """Request to generate a timeline from investigation data."""

    investigation_id: uuid.UUID = Field(..., description="UUID of the investigation")
    evidence_ids: list[uuid.UUID] | None = Field(None, max_length=50, description="Specific evidence to analyze")


class AIReportRequest(BaseModel):
    """Request to generate a full investigation report."""

    investigation_id: uuid.UUID = Field(..., description="UUID of the investigation")


class AIReviewAction(BaseModel):
    """Action on a suggestion (approve or reject)."""

    notes: str | None = Field(None, max_length=2000, description="Review notes")


class AIBulkReviewRequest(BaseModel):
    """Bulk approve/reject suggestions."""

    suggestion_ids: list[uuid.UUID] = Field(..., min_length=1, max_length=100, description="Suggestion UUIDs")
    action: str = Field(..., pattern="^(approve|reject)$", description="Action to apply")
    notes: str | None = Field(None, max_length=2000, description="Optional notes applied to all")


# ── API Response Schemas ──────────────────────────────────────────────────────


class AIJobResponse(BaseModel):
    """Response for an AI job."""

    id: uuid.UUID
    user_id: uuid.UUID
    workspace_id: uuid.UUID
    investigation_id: uuid.UUID | None = None
    job_type: str
    status: str
    provider: str
    model: str
    evidence_ids: list | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    cost: float | None = None
    latency_ms: int | None = None
    cached: bool = False
    error: str | None = None
    result: dict | None = None
    created_at: datetime | None = None
    completed_at: datetime | None = None

    model_config = {"from_attributes": True}


class AISuggestionResponse(BaseModel):
    """Response for a single AI suggestion."""

    id: uuid.UUID
    job_id: uuid.UUID
    investigation_id: uuid.UUID
    suggestion_type: str
    data: dict
    status: str
    reviewed_by: uuid.UUID | None = None
    reviewed_at: datetime | None = None
    review_notes: str | None = None
    created_at: datetime | None = None

    model_config = {"from_attributes": True}


class AIUsageStats(BaseModel):
    """Aggregate AI usage statistics."""

    total_jobs: int = 0
    by_type: dict[str, int] = Field(default_factory=dict)
    by_status: dict[str, int] = Field(default_factory=dict)
    total_tokens_input: int = 0
    total_tokens_output: int = 0
    total_cost: float = 0.0
    average_latency_ms: float = 0.0
    cache_hits: int = 0
    jobs_today: int = 0
    pending_suggestions: int = 0


class PromptVersionResponse(BaseModel):
    """Response for a prompt version."""

    id: uuid.UUID
    name: str
    version: str
    description: str | None = None
    is_active: bool
    created_at: datetime | None = None

    model_config = {"from_attributes": True}


class ProviderInfo(BaseModel):
    """Information about an AI provider."""

    name: str = Field(..., description="Provider identifier")
    display_name: str = Field(..., description="Human-readable name")
    available: bool = Field(..., description="Whether the provider is configured and reachable")
    model: str = Field(..., description="Current model identifier")
    supports_streaming: bool = False
